### ISSUE TITLE
Edit and info buttons overlap info when window is resized

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#11]
![imagen](https://user-images.githubusercontent.com/1389286/79670017-64ccd380-8185-11ea-9b76-75078c76951a.png)

It would be better if they stayed on the right side hidden

**Comment by Deytron** [comment]
So after some testing, I decided to keep it the way it is, because with the buttons to the extreme right, if the windows is not maximized, it becomes impossible to edit game's infos. 
And also, that is Steam's behavior when you resize the window.

![image](https://user-images.githubusercontent.com/20344764/81398533-a5d35a80-9129-11ea-9e53-a9fd86eaa152.png)

What I'll fix is the overlapping if possible.
