### ISSUE TITLE
Grid view: Highlight active item

### ISSUE THREAD

**Issue by tadly** [Deytron/SteamNite#19]
I often like navigation with the keyboard or the d-pad of my controller (using controller companion)
but with newer versions of SteamNite there is no highlight for the current active item anymore.

Am I configuring playnite wrong or was this a explicite decision?

**Comment by Deytron** [comment]
I've taken a look at keyboard navigation, and due to how the animation works when hovering with a mouse, some strange issues occur and keyboard navigation is... troubled. For example, in my testing, using the right arrow key would make the selection go up and down. I haven't figured out why yet.

I can make it work, but I'm gonna need some time, as I don't know what's the exact cause of the issue, and will need a lot of testing.

**Comment by tadly** [comment]
Oh interesting.
I have been using SteamNite for some time now and before updating to 2.3 it worked just fine.

Not sure which version I had prior to that though but I think it might have been a beta build.
The version I had prior still had a white border around the posters and using the arrow keys would navigate just as one would expect.
Maybe this info helps ?

**Comment by shakeyourbunny** [comment]
Would you mind fixing this?

This also happens (at least) in grid view, when I want to select at least one game.
